version: "3"

services:

  redis:
    container_name: newspigeon_redis
    image: redis:7.0.11-alpine

  db:
    container_name: newspigeon_db
    image: postgres:13
    environment:
      POSTGRES_DB: newspigeon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewsPigeon
    depends_on:
      - redis

  web:
    container_name: newspigeon_web
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/newspigeon
  
  celery:
    container_name: newspigeon_celery
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && celery -A newspigeon worker -l INFO -B --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - db
      - redis
    volumes:
      - .:/newspigeon