version: "3"

services:

  redis:
    container_name: newspigeon_redis
    image: redis:7.0.11-alpine

  db:
    container_name: newspigeon_db
    image: postgres:13
    environment:
      POSTGRES_DB: newspigeon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewsPigeon
    depends_on:
      - redis

  web:
    container_name: newspigeon_web
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate && gunicorn --workers=4 --bind=0.0.0.0:8000 newspigeon.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env.dev
    volumes:
      - .:/newspigeon

  celery:
    container_name: newspigeon_celery
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "celery -A newspigeon worker -l INFO -B --scheduler django_celery_beat.schedulers:DatabaseScheduler -Q queue1"
    depends_on:
      - db
      - redis
    volumes:
      - .:/newspigeon

  nginx:
    container_name: newspigeon_nginx
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount your Nginx configuration file
    links:
      - web:web  # Link the Nginx service to the web service
