version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python newspigeon/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: newspigeon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewsPigeon

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    command: python newspigeon/manage.py fetch_articles
    depends_on:
      - db
    volumes:
      - .:/newspigeon
