version: "3"

services:

  redis:
    container_name: newspigeon_redis
    image: redis:7.0.11-alpine
    networks:
      - newspigeon_default

  db:
    container_name: newspigeon_db
    image: postgres:13
    environment:
      POSTGRES_DB: newspigeon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewsPigeon
    ports:
      - "5432:5432"
    depends_on:
      - redis
    networks:
      - newspigeon_default

  web:
    container_name: newspigeon_web
    build:
      context: ./newspigeon  # Adjust the context path to point to your Django project
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate && gunicorn --workers=4 --bind=0.0.0.0:8000 newspigeon.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env.dev
    volumes:
      - ./newspigeon:/app  # Update the volume path for your Django project
      - static_files:/app/static  # Update the volume path for static files
    networks:
      - newspigeon_default

  celery:
    container_name: newspigeon_celery
    build:
      context: ./newspigeon  # Adjust the context path to point to your Django project
      dockerfile: Dockerfile
    command: >
      bash -c "celery -A newspigeon worker -l INFO -B --scheduler django_celery_beat.schedulers:DatabaseScheduler -Q queue1"
    depends_on:
      - db
      - redis
    volumes:
      - ./newspigeon:/app  # Update the volume path for your Django project
    networks:
      - newspigeon_default

volumes:
  static_files:

networks:
  newspigeon_default:
