# Use the official Python image as base
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory inside the container
WORKDIR /newspigeon

# Copy the application code to the container
COPY . /newspigeon/


# Set the entry point to run the cron job
CMD ["python", "manage.py", "fetch_articles"]
