version: "3"

services:

  redis:
    container_name: newspigeon_redis
    image: redis:7.0.11-alpine
    networks:
      - newspigeon_default

  db:
    container_name: newspigeon_db
    image: postgres:13
    environment:
      POSTGRES_DB: newspigeon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewsPigeon
    ports:
      - "5432:5432"
    depends_on:
      - redis
    networks:
      - newspigeon_default

  web:
    container_name: newspigeon_web
    build:
      context: ./newspigeon  # Adjust the context path to point to your Django project (NP_project/newspigeon)
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate && gunicorn --workers=4 --bind=0.0.0.0:8000 newspigeon.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./newspigeon/.env.dev  # Update the path to your Django project's .env file (NP_project/newspigeon/.env.dev)
    volumes:
      - ./newspigeon:/app  # Update the volume path for your Django project (NP_project/newspigeon)
      - static_files:/app/static  # Mount a volume for serving static files
    networks:
      - newspigeon_default

  celery:
    container_name: newspigeon_celery
    build:
      context: ./newspigeon  # Adjust the context path to point to your Django project (NP_project/newspigeon)
      dockerfile: Dockerfile
    command: >
      bash -c "celery -A newspigeon worker -l INFO -B --scheduler django_celery_beat.schedulers:DatabaseScheduler -Q queue1"
    depends_on:
      - db
      - redis
      - web
    volumes:
      - ./newspigeon:/app  # Update the volume path for your Django project (NP_project/newspigeon)
    networks:
      - newspigeon_default

  nginx:
    container_name: newspigeon_nginx
    build:
      context: ./nginx  # Adjust the context path to point to your Nginx directory (NP_project/nginx)
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map port 80 to your host machine
    depends_on:
      - web  # Ensure Nginx starts after your Django application
    volumes:
      - static_files:/app/static  # Mount a volume for serving static files from Nginx
    networks:
      - newspigeon_default

volumes:
  static_files:

networks:
  newspigeon_default:
