# Generated by Django 4.2.4 on 2023-08-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("url", models.URLField()),
                ("date", models.CharField(max_length=100)),
                ("authors", models.TextField()),
                ("domain", models.URLField()),
                ("vector", models.TextField()),
            ],
        ),
    ]
