# Generated by Django 4.2.4 on 2023-08-25 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_newsarticle_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="rating",
            field=models.IntegerField(
                default=-1, validators=[django.core.validators.MaxValueValidator(10)]
            ),
        ),
    ]
